// Settings General Actions Types
export const LOCALE_SET = 'LOCALE_SET'
export const SHOW_MODALLOGIN = 'SHOW_MODALLOGIN'
export const SHOW_MAINMENU = 'SHOW_MAINMENU'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const TOGGLE_BUTTON = 'TOGGLE_BUTTON'
export const PARSE_RESPONSE = 'PARSE_RESPONSE'
export const RESET_RESPONSE = 'RESET_RESPONSE'
export const PARSE_REQUESTTYPE = 'PARSE_REQUESTTYPE'
export const RESET_REQUESTTYPE = 'RESET_REQUESTTYPE'
export const PARSE_ERROR = 'PARSE_ERROR'
export const RESET_ERROR = 'RESET_ERROR'

// Settings General Actions Types
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CREATE_USER = 'CREATE_USER'
export const READALL_USER = 'READALL_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'

// Settings Post Types
export const CREATE_POST = 'CREATE_POST'
export const READALL_POST = 'READALL_POST'
export const READTRANSLATED_POSTS = 'READTRANSLATED_POSTS'
export const READ_POST = 'READ_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'

// Settings Project Types
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const READALL_PROJECT = 'READALL_PROJECT'
export const READ_PROJECT = 'READ_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

// Settings Client Types
export const CREATE_CLIENT = 'CREATE_CLIENT'
export const READALL_CLIENT = 'READALL_CLIENT'
export const UPDATE_CLIENT = 'UPDATE_CLIENT'
export const DELETE_CLIENT = 'DELETE_CLIENT'

// Settings Tutorial Types
export const CREATE_TUTORIAL = 'CREATE_TUTORIAL'
export const READALL_TUTORIAL = 'READALL_TUTORIAL'
export const READ_TUTORIAL = 'READ_TUTORIAL'
export const UPDATE_TUTORIAL = 'UPDATE_TUTORIAL'
export const DELETE_TUTORIAL = 'DELETE_TUTORIAL'

// Settings Translation Types
export const CREATE_TRANSLATION = 'CREATE_TRANSLATION'
export const READALL_TRANSLATION = 'READALL_TRANSLATION'
export const READ_TRANSLATION = 'READ_TRANSLATION'
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION'
export const DELETE_TRANSLATION = 'DELETE_TRANSLATION'

// Settings Image Types
export const ADD_IMAGE = 'ADD_IMAGE'
export const READALL_IMAGE = 'READALL_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'

// Settings Video Types
export const ADD_VIDEO = 'ADD_VIDEO'
export const READALL_VIDEO  = 'READALL_VIDEO'
export const DELETE_VIDEO = 'DELETE_VIDEO'